apiVersion: skaffold/v1
kind: Config
metadata:
  name: webserver
build:
  artifacts:
  - image: scliregistry.azurecr.io/webserver-image
    jib: {}

# Using Jib instead of Docker to update the image for speed
deploy:
  kubectl:
    manifests:
    - webserver.yaml

# Defines profile environments such DEV, PROD
profiles:
  - name: dev
    deploy:
      kubeContext: minikube
    activation:
      - command: dev

  - name: ghost
    deploy:
      kubeContext: sclicluster