apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
        - name: app
          image: scliregistry.azurecr.io/webserver-image:#{Build.BuildId}#
          ports:
            - containerPort: 9999
---
apiVersion: v1
kind: Service
metadata:
  name: webserver-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: kakuna-resource-group
spec:
  selector:
    app: webserver
  ports:
    - port: 80
      targetPort: 9999
  loadBalancerIP: 104.45.183.216
  type: LoadBalancer